// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtslOJ2xoXpiT4kL-ysBhecKkSYIpyl-s',
    appId: '1:976980092466:web:a3f2c09ab6fddf91e8fe2b',
    messagingSenderId: '976980092466',
    projectId: 'reeducation-d7e9c',
    authDomain: 'reeducation-d7e9c.firebaseapp.com',
    storageBucket: 'reeducation-d7e9c.firebasestorage.app',
    measurementId: 'G-C8BWRHV5QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs1Du8BlI528HOzNn6OI_tDybu0iUqK-E',
    appId: '1:976980092466:android:abdb5bec8a942ef1e8fe2b',
    messagingSenderId: '976980092466',
    projectId: 'reeducation-d7e9c',
    storageBucket: 'reeducation-d7e9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn1Hj8EMDTOkvo09caRZ-KmT16Ugu_YDo',
    appId: '1:976980092466:ios:8cfeb5e3ab40771ee8fe2b',
    messagingSenderId: '976980092466',
    projectId: 'reeducation-d7e9c',
    storageBucket: 'reeducation-d7e9c.firebasestorage.app',
    iosBundleId: 'com.example.reeducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn1Hj8EMDTOkvo09caRZ-KmT16Ugu_YDo',
    appId: '1:976980092466:ios:8cfeb5e3ab40771ee8fe2b',
    messagingSenderId: '976980092466',
    projectId: 'reeducation-d7e9c',
    storageBucket: 'reeducation-d7e9c.firebasestorage.app',
    iosBundleId: 'com.example.reeducation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtslOJ2xoXpiT4kL-ysBhecKkSYIpyl-s',
    appId: '1:976980092466:web:19e36c36cbe88c57e8fe2b',
    messagingSenderId: '976980092466',
    projectId: 'reeducation-d7e9c',
    authDomain: 'reeducation-d7e9c.firebaseapp.com',
    storageBucket: 'reeducation-d7e9c.firebasestorage.app',
    measurementId: 'G-5C36W60HW3',
  );
}
